# Generated by Django 5.2.1 on 2025-11-06 17:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL)),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_id', models.CharField(blank=True, max_length=30, null=True)),
                ('numero_id', models.CharField(blank=True, max_length=30, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=100, null=True)),
                ('nivel_educativo', models.CharField(blank=True, max_length=100, null=True)),
                ('nivel_socioeconomico', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto_emergencia', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_emergencia', models.CharField(blank=True, max_length=30, null=True)),
                ('motivo_consulta', models.TextField()),
                ('historia_enfermedad', models.TextField(blank=True, null=True)),
                ('antecedentes_familiares', models.TextField(blank=True, null=True)),
                ('antecedentes_personales', models.TextField(blank=True, null=True)),
                ('antecedentes_tox', models.TextField(blank=True, null=True)),
                ('examen_fisico', models.TextField(blank=True, null=True)),
                ('odontograma_detalle', models.TextField(blank=True, null=True)),
                ('analisis_periodontal', models.TextField(blank=True, null=True)),
                ('higiene', models.CharField(blank=True, max_length=50, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('pronostico', models.CharField(blank=True, max_length=50, null=True)),
                ('plan_tratamiento', models.TextField(blank=True, null=True)),
                ('firma_paciente', models.CharField(blank=True, max_length=150, null=True)),
                ('firma_odontologo', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_firma', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('auxiliar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historias_registradas', to=settings.AUTH_USER_MODEL)),
                ('odontologo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historias_atendidas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias', to='usuarios.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('procedimiento', models.CharField(choices=[('valoracion', 'Valoración (10 min)'), ('exodoncia_simple', 'Exodoncia Simple (40 min)'), ('exodoncia_quirurgica', 'Exodoncia Quirúrgica (1h 30min)'), ('montaje_ortodoncia', 'Montaje Ortodoncia (1h)'), ('control_ortodoncia', 'Control Ortodoncia (30 min)'), ('calza', 'Calza (30 min)'), ('higiene', 'Higiene (20 min)'), ('rehabilitacion', 'Rehabilitación (40 min)'), ('implantes', 'Implantes (1h)'), ('aclaramiento', 'Aclaramiento (1h)')], default='valoracion', max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.paciente')),
            ],
        ),
    ]
